In [1]:
import pandas as pd

In [2]:
house_prices = pd.read_csv('house_prices.csv')

In [3]:
house_prices.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
house_prices.columns.to_series().groupby(house_prices.dtypes).groups

{dtype('int64'): ['Id',
  'MSSubClass',
  'LotArea',
  'OverallQual',
  'OverallCond',
  'YearBuilt',
  'YearRemodAdd',
  'BsmtFinSF1',
  'BsmtFinSF2',
  'BsmtUnfSF',
  'TotalBsmtSF',
  '1stFlrSF',
  '2ndFlrSF',
  'LowQualFinSF',
  'GrLivArea',
  'BsmtFullBath',
  'BsmtHalfBath',
  'FullBath',
  'HalfBath',
  'BedroomAbvGr',
  'KitchenAbvGr',
  'TotRmsAbvGrd',
  'Fireplaces',
  'GarageCars',
  'GarageArea',
  'WoodDeckSF',
  'OpenPorchSF',
  'EnclosedPorch',
  '3SsnPorch',
  'ScreenPorch',
  'PoolArea',
  'MiscVal',
  'MoSold',
  'YrSold',
  'SalePrice'],
 dtype('float64'): ['LotFrontage', 'MasVnrArea', 'GarageYrBlt'],
 dtype('O'): ['MSZoning',
  'Street',
  'Alley',
  'LotShape',
  'LandContour',
  'Utilities',
  'LotConfig',
  'LandSlope',
  'Neighborhood',
  'Condition1',
  'Condition2',
  'BldgType',
  'HouseStyle',
  'RoofStyle',
  'RoofMatl',
  'Exterior1st',
  'Exterior2nd',
  'MasVnrType',
  'ExterQual',
  'ExterCond',
  'Foundation',
  'BsmtQual',
  'BsmtCond',
  'BsmtExposure',
  'BsmtFinType1',
  'BsmtFinType2',
  'Heating',
  'HeatingQC',
  'CentralAir',
  'Electrical',
  'KitchenQual',
  'Functional',
  'FireplaceQu',
  'GarageType',
  'GarageFinish',
  'GarageQual',
  'GarageCond',
  'PavedDrive',
  'PoolQC',
  'Fence',
  'MiscFeature',
  'SaleType',
  'SaleCondition']}

**Задание**:

* разделить набор данных на кваритили по цене продажи;
* узнать средний YearBuilt в квартиле, средний .
* перегруппировать по Functional и узнать среднюю цену в классе продаж.

In [86]:
import numpy as np

# Task 1
quantiles = np.linspace(0,1,5)

In [181]:
quantile_ranges = house_prices["SalePrice"].quantile(quantiles)
groups = house_prices.groupby(pd.cut(house_prices["SalePrice"], quantile_ranges))
# df_list - list of tuples: (quartile range, dataframe)
df_list = []
for gr, df in groups:
    print gr
    print df.head()

(34900, 129975]
    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
8    9          50       RM         51.0     6120   Pave   NaN      Reg
9   10         190       RL         50.0     7420   Pave   NaN      Reg
10  11          20       RL         70.0    11200   Pave   NaN      Reg
17  18          90       RL         72.0    10791   Pave   NaN      Reg
23  24         120       RM         44.0     4224   Pave   NaN      Reg

   LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
8          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
9          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
10         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
17         Lvl    AllPub    ...            0    NaN   NaN        Shed     500
23         Lvl    AllPub    ...            0    NaN   NaN         NaN       0

   MoSold YrSold  SaleType  SaleCondition  SalePrice
8       4   2008        WD        Abnorml     129900
9       1   2008        WD         Normal     118000
10      2   2008        WD         Normal     129500
17     10   2006        WD         Normal      90000
23      6   2007        WD         Normal     129900

[5 rows x 81 columns]
(129975, 163000]
    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
3    4          70       RL         60.0     9550   Pave   NaN      IR1
5    6          50       RL         85.0    14115   Pave   NaN      IR1
12  13          20       RL          NaN    12968   Pave   NaN      IR2
14  15          20       RL          NaN    10920   Pave   NaN      IR1
15  16          45       RM         51.0     6120   Pave   NaN      Reg

   LandContour Utilities    ...     PoolArea PoolQC  Fence MiscFeature  \
3          Lvl    AllPub    ...            0    NaN    NaN         NaN
5          Lvl    AllPub    ...            0    NaN  MnPrv        Shed
12         Lvl    AllPub    ...            0    NaN    NaN         NaN
14         Lvl    AllPub    ...            0    NaN   GdWo         NaN
15         Lvl    AllPub    ...            0    NaN  GdPrv         NaN

   MiscVal MoSold YrSold  SaleType  SaleCondition  SalePrice
3        0      2   2006        WD        Abnorml     140000
5      700     10   2009        WD         Normal     143000
12       0      9   2008        WD         Normal     144000
14       0      5   2008        WD         Normal     157000
15       0      7   2007        WD         Normal     132000

[5 rows x 81 columns]
(163000, 214000]
    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0    1          60       RL         65.0     8450   Pave   NaN      Reg
1    2          20       RL         80.0     9600   Pave   NaN      Reg
7    8          60       RL          NaN    10382   Pave   NaN      IR1
28  29          20       RL         47.0    16321   Pave   NaN      IR1
32  33          20       RL         85.0    11049   Pave   NaN      Reg

   LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
1          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
7          Lvl    AllPub    ...            0    NaN   NaN        Shed     350
28         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
32         Lvl    AllPub    ...            0    NaN   NaN         NaN       0

   MoSold YrSold  SaleType  SaleCondition  SalePrice
0       2   2008        WD         Normal     208500
1       5   2007        WD         Normal     181500
7      11   2009        WD         Normal     200000
28     12   2006        WD         Normal     207500
32      1   2008        WD         Normal     179900

[5 rows x 81 columns]
(214000, 755000]
    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
2    3          60       RL         68.0    11250   Pave   NaN      IR1
4    5          60       RL         84.0    14260   Pave   NaN      IR1
6    7          20       RL         75.0    10084   Pave   NaN      Reg
11  12          60       RL         85.0    11924   Pave   NaN      IR1
13  14          20       RL         91.0    10652   Pave   NaN      IR1

   LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
2          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
4          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
6          Lvl    AllPub    ...            0    NaN   NaN         NaN       0
11         Lvl    AllPub    ...            0    NaN   NaN         NaN       0
13         Lvl    AllPub    ...            0    NaN   NaN         NaN       0

   MoSold YrSold  SaleType  SaleCondition  SalePrice
2       9   2008        WD         Normal     223500
4      12   2008        WD         Normal     250000
6       8   2007        WD         Normal     307000
11      7   2006       New        Partial     345000
13      8   2007       New        Partial     279500

[5 rows x 81 columns]

In [188]:
# Task 2
print "Mean in YearBuilt:"
for gr, df in groups:
    print "{:16} : {}".format(gr, df["YearBuilt"].mean())
    
print "Mean in KitchenAbvGr:"
for gr, df in groups:
    print "{:16} : {}".format(gr, df["KitchenAbvGr"].mean())

Mean in YearBuilt:
(34900, 129975]  : 1945.39835165
(129975, 163000] : 1962.88555858
(163000, 214000] : 1984.64754098
(214000, 755000] : 1992.39226519
Mean in KitchenAbvGr:
(34900, 129975]  : 1.09615384615
(129975, 163000] : 1.07084468665
(163000, 214000] : 1.01912568306
(214000, 755000] : 1.0

In [191]:
func_group = house_prices.groupby("Functional")
for gr, df in func_group:
    print "{:8} : {}".format(gr, df["SalePrice"].mean())

Maj1     : 153948.142857
Maj2     : 85800.0
Min1     : 146385.483871
Min2     : 144240.647059
Mod      : 168393.333333
Sev      : 129000.0
Typ      : 183429.147059